language: php

php:
  - 5.6
  - 5.6
    env GULP=ON
  - 5.6
    env COVERALLS=ON
  - 7
  - nightly

services:
  - mysql

env:
  - DB=mysql
  - TRAVIS_NODE_VERSION="6"

mysql:
  database: travis_ci_twist_test
  username: root
  encoding: utf8

before_install:
  - mysql -V
  - mysql -e "CREATE DATABASE IF NOT EXISTS travis_ci_twist_test;"
  - mysql -e "SHOW DATABASES"
  - if [ "$GULP" = 'ON' ]; then npm install; fi;

install:
  - if [ "$COVERALLS" = 'ON' ]; then composer require satooshi/php-coveralls '~1.0'; fi;
  - php ./tests/install.php
  - if [ "$GULP" = 'ON' ]; then rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION; fi;

before_script:
  - mkdir -p ./build/logs
  - mysql -e "USE travis_ci_twist_test; SHOW TABLES;"
  - sed -i 's/Twist::ServeRoutes(false);/echo "TwistPHP Framework Loaded!\n\n";/g' ./tests/index.php
  - if ["$GULP" = 'ON' ]; then npm install -g gulp; fi;

script:
  - phpunit
  - if [ "$GULP" = 'ON' ]; then gulp test; fi;

notifications:
  on_success: never
  on_failure: always

after_success:
  - if [ "$COVERALLS" = 'ON' ]; then ./vendor/bin/coveralls -v; fi;
