language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

services:
  - mysql

env:
  - DB=mysql

mysql:
  database: travis_ci_twist_test
  username: root
  encoding: utf8

before_script:
  - mysql -V
  - mysql -e "SHOW DATABASES"
  - mysql -e "CREATE DATABASE IF NOT EXISTS travis_ci_twist_test;"
  - mysql -e "SHOW DATABASES"
  - mysql travis_ci_twist_test < dist/twist/Install/install.sql
  - mysql -e "USE travis_ci_twist_test; SHOW TABLES;"

#script: php dist/index.php
script: phpunit dist/index.php tests --verbose

notifications:
  on_success: never
  on_failure: always