language: php

php:
  - 5.3
    env PHPUNIT=ON
  - 5.4
    env PHPUNIT=ON
  - 5.5
    env PHPUNIT=ON
  - 5.6
    env COVERALLS=ON PHPUNIT=ON
  - 5.6
    env GULP=ON
  - 7.0
    env PHPUNIT=ON
  - hhvm
    env PHPUNIT=ON
  - nightly
    env PHPUNIT=ON

services:
  - mysql

env:
  - DB=mysql

mysql:
  database: travis_ci_twist_test
  username: root
  encoding: utf8

before_install:
   - if [ "$PHPUNIT" = 'ON' ]; then mysql -e "CREATE DATABASE IF NOT EXISTS travis_ci_twist_test;"; fi;
   - if [ "$GULP" = 'ON' ]; then npm install; fi;

install:
  - if [ "$COVERALLS" = 'ON' ]; then composer require satooshi/php-coveralls '~1.0'; fi;
  - if [ "$PHPUNIT" = 'ON' ]; then php ./tests/install.php; fi;

before_script:
   - mkdir -p ./build/logs
   - if [ "$PHPUNIT" = 'ON' ]; then mysql -e "USE travis_ci_twist_test; SHOW TABLES;"; fi;
   - if [ "$PHPUNIT" = 'ON' ]; then sed -i 's/Twist::ServeRoutes(false);/echo "TwistPHP Framework Loaded!\n\n";/g' ./tests/index.php; fi;

script:
   - if [ "$PHPUNIT" = 'ON' ]; then phpunit; fi;
   - if [ "$GULP" = 'ON' ]; then gulp test; fi;

notifications:
  on_success: never
  on_failure: always

after_success:
   - if [ "$COVERALLS" = 'ON' ]; then ./vendor/bin/coveralls -v; fi;