language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

services:
  - mysql

env:
  - DB=mysql

mysql:
  database: travis_ci_twist_test
  username: root
  encoding: utf8

before_install:
   - mysql -V
   - mysql -e "CREATE DATABASE IF NOT EXISTS travis_ci_twist_test;"
   - mysql -e "SHOW DATABASES"
   - npm install

install: php ./tests/install.php

before_script:
   - mysql -e "USE travis_ci_twist_test; SHOW TABLES;"
   - ls -lah ./tests
   - sed -i 's/Twist::ServeRoutes(false);/echo "TwistPHP Framework Loaded!\n\n";/g' ./tests/index.php

script:
   - phpunit ./tests/Database.php
   - phpunit ./tests/Settings.php
   - phpunit ./tests/Cache.php
   - phpunit ./tests/Session.php
   - phpunit ./tests/Views.php
   - phpunit ./tests/User.php
   - phpunit ./tests/Curl.php
   - phpunit ./tests/Routes.php
   - gulp test

notifications:
  on_success: never
  on_failure: always